# JavaScript CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys: 
            - v1-repo-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: v1-repo-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          # command: yarn run test --coverage
          command: yarn run test --maxWorkers=2 --ci --coverage --reporters=default --watchAll=false  #--reporters=jest-junit

      - store_artifacts: 
          path: test-results

      - store_test_results:
          path: test-results

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
